import { EventEmitter } from '@angular/core';
import { ViewDimensions, BaseChartComponent, ColorHelper } from '../../src';
export declare class TimelineFilterBarChartComponent extends BaseChartComponent {
    autoScale: boolean;
    schemeType: string;
    valueDomain: number[];
    xAxis: any;
    yAxis: any;
    showXAxisLabel: any;
    showYAxisLabel: any;
    xAxisLabel: any;
    yAxisLabel: any;
    gradient: any;
    showGridLines: boolean;
    animations: boolean;
    onFilter: EventEmitter<{}>;
    dims: ViewDimensions;
    xSet: any;
    xDomain: any;
    yDomain: any;
    seriesDomain: any;
    yScale: any;
    xScale: any;
    xAxisHeight: number;
    yAxisWidth: number;
    timeScale: any;
    colors: ColorHelper;
    scaleType: string;
    transform: string;
    margin: any[];
    initialized: boolean;
    filterId: any;
    filter: any;
    brush: any;
    update(): void;
    getXDomain(): any[];
    getYDomain(): any[];
    getXScale(domain: any, width: any): any;
    getTimeScale(domain: any, width: any): any;
    getYScale(domain: any, height: any): any;
    getScaleType(values: any): string;
    trackBy(index: any, item: any): string;
    setColors(): void;
    updateYAxisWidth({ width }: {
        width: any;
    }): void;
    updateXAxisHeight({ height }: {
        height: any;
    }): void;
    addBrush(): void;
    updateBrush(): void;
}
